# Site settings
title: Daniel Karp's Blog
email: danielkarp@gmail.com
username: karptonite
description: "Daniel writes about programming, mostly. Please excuse the mess!"
baseurl: ""
url: "http://karptonite.com"

# Build settings
markdown: kramdown
permalink: pretty
